services:
  backend:
    build: ./backend
    container_name: backend
    working_dir: /app
    command: npm run start
    environment:
      - PORT=4000
      - NODE_ENV=development
      - TEST=RED_LIGHT
      - AWS_BUCKET=rez541bucket
      - CLOUD=aws
      - SSM_PARAMETER_PATH=/rez541/env/
      - REGION=us-east-1
    networks:
      - cosmosnet
    ports:
      - 4000:4000
  frontend:
      build: ./frontend
      container_name: frontend
      ports:
        - 3000:3000
      networks:
        - cosmosnet
networks:
  cosmosnet:
    driver: bridge
